In [1]:
import pandas as pd

In [2]:
df = pd.read_csv('Customer.csv')

In [3]:
df.head(10)

   user_id             name                       email          signup_date
0        1     David Oneill   jenniferedwards@gmail.com  2024-04-25 19:40:43
1        2  Shelly Martinez         suzanne38@gmail.com  2023-10-26 17:40:51
2        3       Luis Brown         kgarcia@hotmail.com  2023-09-04 23:57:36
3        4     Megan Romero        tinakrause@gmail.com  2023-09-01 23:17:16
4        5     Eric Beltran         rcarter@hotmail.com  2023-10-23 13:16:48
5        6   William Miller           brian13@gmail.com  2024-03-11 05:14:27
6        7    Randall Davis     stevengreen@hotmail.com  2023-09-28 14:04:42
7        8   Michelle Casey  thomaskimberly@hotmail.com  2024-05-06 20:53:11
8        9  William Buckley       thomasdavid@yahoo.com  2022-09-05 17:24:02
9       10   Lawrence Brown  justinbuchanan@example.com  2023-01-09 05:24:34

In [4]:
df['signup_date'] = pd.to_datetime(df['signup_date']).dt.strftime('%Y-%m-%d')

In [5]:
df.head(30)

    user_id               name                        email signup_date
0         1       David Oneill    jenniferedwards@gmail.com  2024-04-25
1         2    Shelly Martinez          suzanne38@gmail.com  2023-10-26
2         3         Luis Brown          kgarcia@hotmail.com  2023-09-04
3         4       Megan Romero         tinakrause@gmail.com  2023-09-01
4         5       Eric Beltran          rcarter@hotmail.com  2023-10-23
5         6     William Miller            brian13@gmail.com  2024-03-11
6         7      Randall Davis      stevengreen@hotmail.com  2023-09-28
7         8     Michelle Casey   thomaskimberly@hotmail.com  2024-05-06
8         9    William Buckley        thomasdavid@yahoo.com  2022-09-05
9        10     Lawrence Brown   justinbuchanan@example.com  2023-01-09
10       11          Kyle Ross       alyssawarren@yahoo.com  2024-05-19
11       12        Jose Fisher  medinaelizabeth@example.com  2023-02-06
12       13       Brenda Zhang          james37@hotmail.com  2023-07-31
13       14       Amanda Ortiz     nicholsdonna@example.com  2023-07-29
14       15        Craig Stout     matthewmcbride@yahoo.com  2022-11-16
15       16      Carmen Gordon           zjohnson@yahoo.com  2024-04-05
16       17       Leslie Yates          ahaynes@hotmail.com  2024-03-07
17       18      Megan Sanders           whouston@yahoo.com  2022-09-09
18       19        Mary Adkins            donna30@yahoo.com  2022-09-12
19       20  Danielle Erickson      nicholasjones@yahoo.com  2024-04-20
20       21    Alexander Terry     justinphillips@yahoo.com  2023-02-10
21       22   Rickey Velasquez    goodwinmorgan@hotmail.com  2024-06-08
22       23     Aaron Mitchell              gutierrezjoshua  2023-01-03
23       24       Linda Romero           gstanley@gmail.com  2024-04-12
24       25      Bethany Hurst        clarkederek@yahoo.com  2023-01-19
25       26     Courtney Green           imarquez@gmail.com  2024-08-01
26       27   Nicole Rodriguez              uyork@gmail.com  2023-08-23
27       28         Kevin Reed      donaldcurry@example.com  2023-10-31
28       29        Austin King           rsmith@hotmail.com  2023-04-04
29       30   Brittney Jackson           fsingh@hotmail.com  2024-01-31

In [6]:
df = df[df['email'].str.contains(r'^[\w\.-]+@[\w\.-]+\.com$', regex=True)]

In [7]:
df.head(30)

    user_id               name                        email signup_date
0         1       David Oneill    jenniferedwards@gmail.com  2024-04-25
1         2    Shelly Martinez          suzanne38@gmail.com  2023-10-26
2         3         Luis Brown          kgarcia@hotmail.com  2023-09-04
3         4       Megan Romero         tinakrause@gmail.com  2023-09-01
4         5       Eric Beltran          rcarter@hotmail.com  2023-10-23
5         6     William Miller            brian13@gmail.com  2024-03-11
6         7      Randall Davis      stevengreen@hotmail.com  2023-09-28
7         8     Michelle Casey   thomaskimberly@hotmail.com  2024-05-06
8         9    William Buckley        thomasdavid@yahoo.com  2022-09-05
9        10     Lawrence Brown   justinbuchanan@example.com  2023-01-09
10       11          Kyle Ross       alyssawarren@yahoo.com  2024-05-19
11       12        Jose Fisher  medinaelizabeth@example.com  2023-02-06
12       13       Brenda Zhang          james37@hotmail.com  2023-07-31
13       14       Amanda Ortiz     nicholsdonna@example.com  2023-07-29
14       15        Craig Stout     matthewmcbride@yahoo.com  2022-11-16
15       16      Carmen Gordon           zjohnson@yahoo.com  2024-04-05
16       17       Leslie Yates          ahaynes@hotmail.com  2024-03-07
17       18      Megan Sanders           whouston@yahoo.com  2022-09-09
18       19        Mary Adkins            donna30@yahoo.com  2022-09-12
19       20  Danielle Erickson      nicholasjones@yahoo.com  2024-04-20
20       21    Alexander Terry     justinphillips@yahoo.com  2023-02-10
21       22   Rickey Velasquez    goodwinmorgan@hotmail.com  2024-06-08
23       24       Linda Romero           gstanley@gmail.com  2024-04-12
24       25      Bethany Hurst        clarkederek@yahoo.com  2023-01-19
25       26     Courtney Green           imarquez@gmail.com  2024-08-01
26       27   Nicole Rodriguez              uyork@gmail.com  2023-08-23
27       28         Kevin Reed      donaldcurry@example.com  2023-10-31
28       29        Austin King           rsmith@hotmail.com  2023-04-04
29       30   Brittney Jackson           fsingh@hotmail.com  2024-01-31
30       31        Nathan Bell   nguyenjeanette@hotmail.com  2022-11-10

In [8]:
df['domain'] = df['email'].str.split('@').str[1]

In [9]:
df.head()

,user_id,name,email,signup_date,domain
0,1,David Oneill,jenniferedwards@gmail.com,2024-04-25,gmail.com
1,2,Shelly Martinez,suzanne38@gmail.com,2023-10-26,gmail.com
2,3,Luis Brown,kgarcia@hotmail.com,2023-09-04,hotmail.com
3,4,Megan Romero,tinakrause@gmail.com,2023-09-01,gmail.com
4,5,Eric Beltran,rcarter@hotmail.com,2023-10-23,hotmail.com

In [10]:
df = df.drop_duplicates(subset='email', keep='first')

In [11]:
df.to_csv('New_Customer.csv', index=False)